import { DashboardData } from "@/types/dashboard";

export const mockDashboardData: DashboardData = {
  accounts: [
    {
      id: "acc-1",
      name: "prod-main",
      tenancy: "ocid1.tenancy.oc1..prodmain",
      region: "us-ashburn-1",
      status: "healthy",
      instanceCount: 6,
      lastSync: "2 分钟前",
    },
    {
      id: "acc-2",
      name: "hk-main",
      tenancy: "ocid1.tenancy.oc1..hkmain",
      region: "ap-hongkong-1",
      status: "healthy",
      instanceCount: 4,
      lastSync: "5 分钟前",
    },
    {
      id: "acc-3",
      name: "backup",
      tenancy: "ocid1.tenancy.oc1..backup",
      region: "us-phoenix-1",
      status: "warning",
      instanceCount: 2,
      lastSync: "18 分钟前",
    },
  ],
  instances: [
    {
      id: "vm-1",
      accountId: "acc-1",
      name: "web-prod-01",
      accountName: "prod-main",
      region: "us-ashburn-1",
      status: "running",
      ip: "129.146.10.10",
      ipv6: "-",
      shape: "VM.Standard.A1.Flex",
    },
    {
      id: "vm-2",
      accountId: "acc-1",
      name: "queue-worker",
      accountName: "prod-main",
      region: "us-ashburn-1",
      status: "stopped",
      ip: "-",
      ipv6: "-",
      shape: "VM.Standard.E4.Flex",
    },
    {
      id: "vm-3",
      accountId: "acc-2",
      name: "hk-edge-01",
      accountName: "hk-main",
      region: "ap-hongkong-1",
      status: "running",
      ip: "129.146.88.20",
      ipv6: "2408:4001:abcd::10",
      shape: "VM.Standard.A1.Flex",
    },
    {
      id: "vm-4",
      accountId: "acc-3",
      name: "db-replica",
      accountName: "backup",
      region: "us-phoenix-1",
      status: "starting",
      ip: "129.146.77.33",
      ipv6: "-",
      shape: "VM.Standard.E5.Flex",
    },
  ],
  logs: [
    {
      id: "log-1",
      time: "2026-03-18 10:12",
      user: "admin",
      account: "prod-main",
      instance: "web-prod-01",
      action: "重启",
      result: "success",
      message: "Nginx 已成功重启。",
    },
    {
      id: "log-2",
      time: "2026-03-18 10:15",
      user: "admin",
      account: "hk-main",
      instance: "hk-edge-01",
      action: "同步",
      result: "success",
      message: "实例列表已刷新。",
    },
    {
      id: "log-3",
      time: "2026-03-18 10:18",
      user: "admin",
      account: "backup",
      instance: "db-replica",
      action: "开机",
      result: "failed",
      message: "配额检查失败，请确认容量。",
    },
  ],
};
